JumboCode/South-Florida-Jewish-Academy

- README.md
Added in my info on the README
#22
> #22 README - Victoria

- README.md
Look at README to see new line
> SFJA-13: README- Hally

- README.md
> SFJA-19: README Jacqueline

- bin/resetDatabase.py
> synced all form_ids with corresponding parents and students

- api/database/studentsDOM.py
- api/database/testDB.py
- api/run.py
> Sfja 51 - Created endpoint to access student data

- .gitignore
- api/database/testDB.py
- api/database/usersDOM.py
- api/run.py
- api/tests.py
- bin/resetDatabase.py
Created UsersDOM file with functions and tests.
#60
> #60: Created UsersDOM file

- api/database/testDB.py
- api/database/usersDOM.py
- api/tests.py
- bin/resetDatabase.py
> #60: Added usersDOM functions and test cases

- api/database/assets/audit_mapper.py
- api/database/testDB.py
- api/run.py
- bin/resetDatabase.py
#74 : 
-TODO:  I have to add a dictionary to map actions (strings) to a value for some good ~ modularity ~
> Record actions for each endpoint

- sfja/src/components/AddStudent/FormSelector.js
- sfja/src/components/AddStudent/Input.js
Bug should be fixed, no error message should print
> Sfja 99: Fix update during render bug

- sfja/src/components/AddStudent/AddStudent.js
- sfja/src/components/AddStudent/FormSelector.js
- sfja/src/components/AddStudent/Input.js
Added a bunch of material ui elements and flexes
> #104 Adding Student Paper

- sfja/src/components/AddStudent/AddStudent.js
- sfja/src/components/AddStudent/FormSelector.js
- sfja/src/components/Dashboard.js
- sfja/src/components/Header.css
- sfja/src/components/Header.js
- sfja/src/components/Students/Student.js
- sfja/src/components/Students/Students.js
- sfja/src/components/Upload.js
- sfja/src/index.js
> Going to new header! :) #103

- sfja/src/components/FormManager/BlankFormBuilder/DemoBar.js
- sfja/src/components/ParentDash/FormDisplay.js
Current master has the incorrect directory for `apiUr` in Demobar.js
Added extra `../`to fix
> #141 - Linting and directory issue.

- sfja/src/components/Students/Students.js
- sfja/src/components/Students/Styles.js
Will need to position search bar at top of screen, but functionality should be good.
> sfja-117: Added search bar

- api/run.py
@jhuang09 check this out
This should help us with a performance boost too with relatively low security compromises
> #159 Adding temp token storage based on user_info

- sfja/src/components/Students/Filters.js
- sfja/src/components/Students/Students.js
Added filters on students page
> SJFA-116 Filtering on Students

- api/database/studentsDOM.py
- api/run.py
- sfja/src/components/Students/Students.js
Try deleting a student
If not admin user, column does not exist and endpoint does not allow access
(you can test this part by changing line 299 to an empty list)
> SFJA-176 Delete Student

- api/database/studentsDOM.py
- api/run.py
- sfja/src/components/Administration/Administration.js
- sfja/src/components/Administration/AuthMessage.js
- sfja/src/components/Administration/ChangeGrades.js
* new components under `Administration` to increment or decrement all grades
* new "Authorizing..." message
* realized we had a redundant function in `studentDOM.py`; deleted it
> SFJA-178: Increment students' grades

- sfja/src/App.js
- sfja/src/components/Administration/Administration.js
- sfja/src/components/Administration/Audit.js
- sfja/src/components/Header.js
Moved audit to under the administration tab
> SFJA-180: Audit under administration

- sfja/src/components/Students/Students.js
After deletion, filters will refresh and maintain old previous filtration settings
> SFJA-184 Update filters with student removal

- sfja/src/components/Students/Students.js
* try a query that would have had to been case sensitive before
> SFJA-189 Case Insensitive Queries

- api/database/parentsDOM.py
- api/run.py
- sfja/src/components/ParentDash/ParentDash.js
New parent dash that displays their name and email
> SFJA-196 Parent Dash

- sfja/src/App.js
- sfja/src/components/LoginPage.js
- sfja/src/components/Logout.js
- sfja/src/components/StudentProfile/StudentProfile.js
- sfja/src/components/Students/Filters.js
- sfja/src/components/Students/Students.js
Make a query, change filters, or change sorting. Then, click out, then click back -- selections restored!
> SFJA-196 Caching student info

- sfja/src/components/FormManager/FormManager.js
- sfja/src/components/StudentProfile/Forms.js
- sfja/src/components/Students/Filters.js
- sfja/src/components/Students/Students.js
- every table now has highlighters and selectors
- enclosed icons of table selectors in `<Button/>` for nicer UI
> SFJA-206: Highlighters for table selections

- sfja/src/components/StudentProfile/FormViewer.js
> SFJA 203 Disable form edits by default

- api/run.py
- sfja/src/components/StudentProfile/FormViewer.js
I need some feedback so I guess I will open a PR?
1. I had to do two fetches in the componentDidMount. I mean it works.. but is it the right way to do it? 
2. I couldn't get the catch(error).... part to work after making those two fetches.
3. I dont know how to access the auth0 website where I can manipulate the roles of the person, but I looked at the response of the fetch call and tried disabling the switch and then checking with the authorized bool.
Let me know when you are free tomorrow to discuss!
> #226:Non-admin editing

- sfja/src/components/AddStudent/AddStudent.js
- sfja/src/components/AddStudent/FormSelector.js
- sfja/src/components/Administration/Administration.js
- sfja/src/components/Administration/Audit.js
- sfja/src/components/Administration/ChangeGrades.js
- sfja/src/components/Administration/ClearLogins.js
- sfja/src/components/Administration/DataExports.js
- sfja/src/components/Administration/DeleteArchived.js
- sfja/src/components/FormManager/BlankFormBuilder/BlankFormBuilder.js
- sfja/src/components/FormManager/BlankFormBuilder/DemoBar.js
- sfja/src/components/FormManager/FormManager.js
- sfja/src/components/FormManager/PreviewBlankForm.js
- sfja/src/components/LoginPage.js
- sfja/src/components/Logout.js
- sfja/src/components/StudentProfile/AdminZone.js
- sfja/src/components/StudentProfile/DocumentUpload.js
- sfja/src/components/StudentProfile/FormViewer.js
- sfja/src/components/StudentProfile/Parents.js
- sfja/src/components/StudentProfile/ProfileEdit.js
- sfja/src/components/StudentProfile/ResendForms.js
- sfja/src/components/StudentProfile/StudentProfile.js
- sfja/src/components/Students/Students.js
- sfja/src/utils/Auth0Wrapper.js
@Antranduc you should be happy now :)
> SFJA 243 - No more cookie auth0
